#!/usr/bin/env bash
# close-milestone.sh — archive a COMPLETED roadmap and scaffold the next one, but REFUSE to
# close while any work or unresolved finding remains. This is the deterministic replacement for
# the old milestone prose ("ask whether to proceed anyway") — there is NO bypass flag by design.
#
# Refuses (exit 1) when:
#   - docs/ROADMAP.md has any open "- [ ]" item, OR
#   - NEXT_FINDINGS.md exists (an unresolved evaluator finding), OR
#   - docs/ROADMAP.md has no phases at all (nothing to close — also makes re-runs safe).
# On success: git mv docs/ROADMAP.md -> docs/archive/ROADMAP-<label>.md (label = --name arg,
# else a VERSION file, else the latest git tag, else the UTC date), write a fresh empty
# docs/ROADMAP.md, and reset the docs/STATE.md auto-block to point at the next scope.
#
# Usage: bash scripts/close-milestone.sh [--name <label>]
set -uo pipefail
cd "$(git rev-parse --show-toplevel 2>/dev/null || echo .)" || exit 1
ROADMAP="docs/ROADMAP.md"
STATE="docs/STATE.md"

NAME=""
while [ $# -gt 0 ]; do
  case "$1" in
    --name) NAME="${2:-}"; shift 2 ;;
    *) echo "close-milestone: unknown argument '$1'" >&2; exit 1 ;;
  esac
done

refuse() { echo "close-milestone: REFUSED — $1" >&2; exit 1; }

[ -f "$ROADMAP" ] || refuse "no $ROADMAP to close."
grep -qE '\- \[[ xX]\]' "$ROADMAP" 2>/dev/null || refuse "no phases in $ROADMAP — nothing to close."
grep -q '\- \[ \]' "$ROADMAP" 2>/dev/null && refuse "open items remain in $ROADMAP — finish or remove them first."
[ -f NEXT_FINDINGS.md ] && refuse "NEXT_FINDINGS.md exists (an unresolved evaluator finding) — resolve it first."

# Pick the archive label.
if [ -z "$NAME" ]; then
  if [ -f VERSION ]; then
    NAME=$(tr -d '[:space:]' < VERSION)
  elif NAME=$(git describe --tags --abbrev=0 2>/dev/null) && [ -n "$NAME" ]; then
    :
  fi
fi
[ -z "$NAME" ] && NAME=$(date -u +%Y%m%d 2>/dev/null || echo milestone)

mkdir -p docs/archive
DEST="docs/archive/ROADMAP-$NAME.md"
# Never clobber existing history — suffix if a same-named archive already exists.
[ -e "$DEST" ] && DEST="docs/archive/ROADMAP-$NAME-$(date -u +%H%M%S 2>/dev/null || echo dup).md"
git mv "$ROADMAP" "$DEST" 2>/dev/null || mv "$ROADMAP" "$DEST"

cat > "$ROADMAP" <<'MD'
# Roadmap

<!--
Author phases here (use the `roadmap` skill, or the `milestone` skill Mode A). Each phase is:
a "## Phase N — <goal>" heading, one unchecked checkbox line per task, a "Done when:" line with
an observable/machine-checkable condition, and a "Mode: loopable | supervised" line.
See docs/archive/ for the previous milestone's phases as examples.
-->
MD

# Reset the STATE auto-block (if present) to point at authoring the next scope.
if [ -f "$STATE" ] && grep -qF '<!-- lean:auto:begin -->' "$STATE"; then
  awk -v d="$NAME" '
    /<!-- lean:auto:begin -->/ {
      print
      print "_Auto-generated by scripts/tick.sh on each roadmap tick — do not edit between these markers._"
      print ""
      print "- Milestone " d " closed. Author the next scope, then plan its first phase."
      skip=1; next
    }
    /<!-- lean:auto:end -->/ { print; skip=0; next }
    !skip { print }
  ' "$STATE" > "$STATE.tmp" && mv "$STATE.tmp" "$STATE"
fi

echo "close-milestone: ✓ archived $ROADMAP → $DEST; fresh roadmap created. Author the next scope (roadmap skill)."
