#!/usr/bin/env bash
# tick.sh — the SINGLE roadmap-completion gate. The ONLY path that flips "- [ ]" → "- [x]".
#
# Called by scripts/autopilot.sh (headless) AND the in-session /wrap flow, so that NO command,
# prompt, or model instruction can mark roadmap work complete without passing the SAME checks.
# Interactive work stays lightweight; completion marking is strict.
#
# Verifies (ALL required — any failure is fail-closed, ROADMAP left byte-identical):
#   1. target heading present verbatim in docs/ROADMAP.md
#   2. evaluator PASS evidence: .claude/.phase-grade has run_id == HEAD and verdict == PASS
#   3. fresh test evidence: .claude/.tick-evidence.json (from scripts/test-evidence.sh) is valid
#      JSON with run_id == HEAD AND (passed == true, OR passed == null with grade no_tests_ok=1)
#   4. secret scan of the phase diff is clean
#   5. high-stakes paths NOT touched (path match; content match added in Phase 2B)
#   6. the target phase still has an open "- [ ]" item
#   7. after ticking, the open-item count strictly dropped
#
# Side effects: ticks ROADMAP. (Phase 2B adds: update the docs/STATE.md machine block.)
# Does NOT commit, push, open a PR, run the evaluator, or archive — the CALLER owns those.
#
# Usage: bash scripts/tick.sh ["<exact phase heading>"]   (defaults to .claude/.phase-ready)
# Exit:  0 = ticked · 1 = refused (stop) · 3 = high-stakes (supervised; caller must NOT push)
set -uo pipefail
cd "$(git rev-parse --show-toplevel 2>/dev/null || echo .)" || exit 1

ROADMAP="docs/ROADMAP.md"
GRADE=".claude/.phase-grade"
EVIDENCE=".claude/.tick-evidence.json"

refuse() {
  echo "tick: REFUSED — $1" >&2
  printf 'tick refused: %s\n' "$1" > NEXT_FINDINGS.md 2>/dev/null || true
  exit 1
}

# update_state <ticked-heading>: deterministically rewrite the machine-managed block in
# docs/STATE.md (between the markers) with the last ticked phase + the next open phase, so a
# fresh session never reads a STATE that lags the roadmap. The model's narrative OUTSIDE the
# markers is left untouched. If the markers are absent, the block is appended once.
STATE_BEGIN='<!-- lean:auto:begin -->'
STATE_END='<!-- lean:auto:end -->'
update_state() {
  local ticked="$1" state="docs/STATE.md"
  [ -f "$state" ] || return 0
  local stamp next_h next_t blockfile
  stamp=$(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || echo "unknown")
  # First "## " heading that still has an open "- [ ]" item, and that item's text.
  next_h=$(awk '/^## /{h=$0} /- \[ \]/ && h!=""{print h; exit}' "$ROADMAP")
  next_t=$(awk '/^## /{h=$0} /- \[ \]/ && h!=""{sub(/^[[:space:]]*- \[ \] /,""); print; exit}' "$ROADMAP")
  blockfile=$(mktemp 2>/dev/null || echo "$state.block.$$")
  {
    echo "$STATE_BEGIN"
    echo "_Auto-generated by scripts/tick.sh on each roadmap tick — do not edit between these markers._"
    echo ""
    echo "- Last ticked: ${ticked#\#\# }"
    echo "- Updated: ${stamp}"
    if [ -n "$next_h" ]; then
      echo "- Next phase: ${next_h#\#\# }"
      echo "- Next action: ${next_t:-<see roadmap>}"
    else
      echo "- Roadmap complete — every phase is ticked. Close it with scripts/close-milestone.sh (or the milestone skill)."
    fi
    echo "$STATE_END"
  } > "$blockfile"
  if grep -qF "$STATE_BEGIN" "$state"; then
    awk -v b="$STATE_BEGIN" -v e="$STATE_END" -v bf="$blockfile" '
      BEGIN { while ((getline l < bf) > 0) blk = blk l "\n" }
      $0==b { printf "%s", blk; skip=1; next }
      $0==e { if (skip) { skip=0; next } }
      !skip { print }
    ' "$state" > "$state.tmp" && mv "$state.tmp" "$state"
  else
    { echo ""; cat "$blockfile"; } >> "$state"
  fi
  rm -f "$blockfile" 2>/dev/null || true
}

# --- 1. target heading ---
heading="${1:-}"
[ -z "$heading" ] && heading=$(cat .claude/.phase-ready 2>/dev/null || true)
[ -z "$heading" ] && refuse "no phase heading (pass one, or write .claude/.phase-ready)"
[ -f "$ROADMAP" ] || refuse "missing $ROADMAP"
# Exact FULL-LINE match (-x): every downstream awk block consumes the heading via `$0==ph`, so a
# mere substring that isn't a standalone `## ` line would pass here yet match nothing later. Make
# the existence check agree with the consumption — refuse loudly instead of failing silently.
grep -qxF "$heading" "$ROADMAP" || refuse "phase heading not found as an exact line in roadmap: '$heading'"

HEAD=$(git rev-parse HEAD 2>/dev/null) || refuse "not a git repo / no HEAD"
command -v jq >/dev/null 2>&1 || refuse "jq required to read evidence"

# --- 2. evaluator PASS evidence ---
[ -f "$GRADE" ] || refuse "missing evaluator grade evidence ($GRADE) — run the evaluator first"
g_run=$(grep -E '^run_id=' "$GRADE" | head -1 | cut -d= -f2- || true)
g_verdict=$(grep -E '^verdict=' "$GRADE" | head -1 | cut -d= -f2- || true)
g_notests=$(grep -E '^no_tests_ok=' "$GRADE" | head -1 | cut -d= -f2- || true)
[ "$g_run" = "$HEAD" ] || refuse "grade evidence is stale (grade run_id '$g_run' != HEAD '$HEAD')"
[ "$g_verdict" = "PASS" ] || refuse "evaluator verdict is not PASS (got '$g_verdict')"

# --- 3. fresh test evidence ---
[ -f "$EVIDENCE" ] || refuse "missing test evidence ($EVIDENCE) — run scripts/test-evidence.sh"
jq empty "$EVIDENCE" >/dev/null 2>&1 || refuse "test evidence is not valid JSON"
e_run=$(jq -r '.run_id // ""' "$EVIDENCE")
e_passed=$(jq -r '.passed' "$EVIDENCE" 2>/dev/null || echo "missing")
[ "$e_run" = "$HEAD" ] || refuse "test evidence is stale (evidence run_id '$e_run' != HEAD '$HEAD')"
case "$e_passed" in
  true) : ;;
  null)
    [ "$g_notests" = "1" ] \
      || refuse "no test suite (passed:null) and the evaluator did not confirm NO_TESTS_OK" ;;
  *) refuse "tests are not green (passed=$e_passed)" ;;
esac

# --- 4 & 5. secret + high-stakes over the WHOLE phase diff ---
# Require .claude/.phase-base: without it we'd fall back to HEAD~1 and silently NARROW the secret
# and high-stakes scans to the last commit only, missing earlier phase commits. Fail closed.
BASE=$(cat .claude/.phase-base 2>/dev/null || true)
[ -n "$BASE" ] || refuse "missing .claude/.phase-base — cannot determine the phase scope to scan (fail-closed)"
RANGE="${BASE}..HEAD"
[ -f .claude/lib/_secret-scan.sh ] && . .claude/lib/_secret-scan.sh 2>/dev/null || true
[ -f .claude/lib/_high-stakes.sh ] && . .claude/lib/_high-stakes.sh 2>/dev/null || true

command -v secret_scan_diff  >/dev/null 2>&1 || refuse "secret-scan library unavailable — fail-closed"
command -v high_stakes_match >/dev/null 2>&1 || refuse "high-stakes library unavailable — fail-closed"

SF=$(secret_scan_diff "$RANGE"); SRC=$?
if [ "$SRC" -ne 0 ]; then
  echo "tick: REFUSED — secret(s) in phase diff ($RANGE):" >&2
  printf '%s\n' "$SF" | sed 's/^/    /' >&2
  printf 'tick refused: secret in phase diff\n%s\n' "$SF" > NEXT_FINDINGS.md 2>/dev/null || true
  exit 1
fi

CHANGED=$(git diff --name-only "$RANGE" 2>/dev/null || true)
if HS=$(high_stakes_match "$CHANGED"); then
  echo "tick: ⛔ HIGH-STAKES paths changed — supervised review required, NOT ticking:" >&2
  printf '%s\n' "$HS" | sed 's/^/    /' >&2
  exit 3
fi
# Content-level high-stakes: destructive operations in a benignly-named file. Scan the
# ADDED lines of the whole phase diff. A hit forces supervised review (exit 3), same as a path.
if command -v high_stakes_content_match >/dev/null 2>&1; then
  ADDED=$(git diff "$RANGE" --unified=0 2>/dev/null | grep -E '^\+' | grep -Ev '^\+\+\+' || true)
  if HC=$(high_stakes_content_match "$ADDED"); then
    echo "tick: ⛔ HIGH-STAKES content in phase diff — supervised review required, NOT ticking:" >&2
    printf '%s\n' "$HC" | sed 's/^/    /' >&2
    exit 3
  fi
fi

# Mode: supervised — the author flagged this phase as human-on-the-loop. Enforce it (the tag
# used to be advisory/unparsed): refuse to auto-tick, same supervised exit as a high-stakes hit.
PHASE_MODE=$(awk -v ph="$heading" '
  $0==ph {inphase=1; next}
  /^## / && inphase {inphase=0}
  inphase && /^[[:space:]]*Mode:/ {print tolower($0); exit}
' "$ROADMAP")
case "$PHASE_MODE" in
  *supervised*)
    echo "tick: ⛔ phase is marked 'Mode: supervised' — human review required, NOT auto-ticking." >&2
    exit 3 ;;
esac

# --- 6. target phase still has an open item ---
open_in_phase=$(awk -v ph="$heading" '
  $0==ph {inphase=1; next}
  /^## / && inphase {inphase=0}
  inphase && /- \[ \]/ {c++}
  END {print c+0}
' "$ROADMAP")
[ "${open_in_phase:-0}" -gt 0 ] || refuse "no open '- [ ]' items under '$heading' (already ticked?)"

# --- 7. tick, then verify the count strictly dropped ---
before=$(grep -c '\- \[ \]' "$ROADMAP" 2>/dev/null)
awk -v ph="$heading" '
  $0==ph {inphase=1; print; next}
  /^## / && inphase {inphase=0}
  inphase {gsub(/- \[ \]/, "- [x]")}
  {print}
' "$ROADMAP" > "$ROADMAP.tmp" && mv "$ROADMAP.tmp" "$ROADMAP"
after=$(grep -c '\- \[ \]' "$ROADMAP" 2>/dev/null)
if [ "$after" -ge "$before" ]; then
  refuse "tick changed no items under '$heading' (roadmap left unchanged)"
fi

rm -f .claude/.phase-ready .claude/.phase-grade 2>/dev/null || true
update_state "$heading"
echo "tick: ✓ ticked '$heading' ($((before - after)) item(s))"
exit 0
